def trim(val):
    return val.strip()

converters_trim={
    'RAT.NUM_ATIVIDADE':trim,
    'NAT.CODIGO':trim,
    'NAT.DESCRICAO':trim,
    'DTA_HRA_INCLUSAO':trim,
    'DTA_INICIO':trim,
    'HRA_INICIO':trim,
    'DTA_TERMINO':trim,
    'HRA_TERMINO':trim,
    'DES_ALVO_EVENTO':trim,
    'DES_LUGAR':trim,
    'NOM_OPERACAO':trim,
    'COD_UNIDADE_SERVICO':trim,
    'NOM_UNID_RESPONSAVEL':trim,
    'TIPO_LOGRADOURO':trim,
    'LOGRADOURO':trim,
    'DES_ENDERECO':trim,
    'NUM_ENDERECO':trim,
    'COMPLEMENTO_ALFA':trim,
    'COMPLEMENTO_ENDERECO':trim,
    'NUM_COMPLEMENTAR':trim,
    'COD_BAIRRO':trim,
    'NOME_BAIRRO':trim,
    'TIPO_LOGRADOURO2':trim,
    'LOGRADOURO2':trim,
    'DES_ENDERECO2':trim,
    'COD_MUNICIPIO':trim,
    'MUNICIPIO':trim,
    'LATITUDE':trim,
    'LONGITUDE':trim,
    'COD_UNIDADE_AREA':trim,
    'NOM_UNIDADE_AREA':trim,
    'DIGITADOR':trim
}